<?php

namespace Database\Seeders;

use App\Models\Tags;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TagsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tags = [
            [
                'tag' => 'Water Sports',
                'link' => ''
            ],
            [
                'tag' => 'Ferry Booking',
                'link' => ''
            ],
            [
                'tag' => 'Cab Rental',
                'link' => ''
            ],
            [
                'tag' => 'Bike Rental',
                'link' => ''
            ],

            [
                'tag' => 'Havelock Island',
                'link' => ''
            ],

            [
                'tag' => 'Port Blair',
                'link' => ''
            ],
            [
                'tag' => 'Neil Island',
                'link' => ''
            ],
            [
                'tag' => 'Baratang Island',
                'link' => ''
            ],
            [
                'tag' => 'Mayabunder Island',
                'link' => ''
            ],
            [
                'tag' => 'Diglipur Island',
                'link' => ''
            ],
            [
                'tag' => 'Rangat Island',
                'link' => ''
            ],
            [
                'tag' => 'Andaman Tour Packages',
                'link' => ''
            ],
            [
                'tag' => 'Honeymoon Packages',
                'link' => ''
            ],
            [
                'tag' => 'Family Packages',
                'link' => ''
            ],
            [
                'tag' => 'Andaman tour package',
                'link' => ''
            ],
            [
                'tag' => 'Andaman Nicobar tour package',
                'link' => ''
            ],
            [
                'tag' => 'Andaman couple tour package',
                'link' => ''
            ],
            [
                'tag' => 'Andaman family tour package',
                'link' => ''
            ],
            [
                'tag' => 'Andaman group tour package',
                'link' => ''
            ],
            [
                'tag' => 'Budget Andaman tour package',
                'link' => ''
            ],
            [
                'tag' => 'Luxury Andaman package',
                'link' => ''
            ],
            [
                'tag' => 'Cheap Andaman tour package',
                'link' => ''
            ],
            [
                'tag' => 'Best Andaman tour package',
                'link' => ''
            ],
            [
                'tag' => '3 nights 4 days Andaman package',
                'link' => ''
            ],
            [
                'tag' => '4 nights 5 days Andaman tour',
                'link' => ''
            ],
            [
                'tag' => '5 nights 6 days Andaman itinerary',
                'link' => ''
            ],
            [
                'tag' => '6 nights 7 days Andaman package',
                'link' => ''
            ],
            [
                'tag' => 'Short Andaman trip package',
                'link' => ''
            ],
            [
                'tag' => 'Havelock island tour package',
                'link' => ''
            ],
            [
                'tag' => 'Neil island tour package',
                'link' => ''
            ],

            [
                'tag' => 'Port Blair tour package',
                'link' => ''
            ],
            [
                'tag' => 'Andaman multi-island package',
                'link' => ''
            ],
            [
                'tag' => 'Andaman adventure tour package',
                'link' => ''
            ],
            [
                'tag' => 'Andaman water sports package',
                'link' => ''
            ],
            [
                'tag' => 'Andaman honeymoon packages for couples',
                'link' => ''
            ],
            [
                'tag' => 'Custom Andaman tour package',
                'link' => ''
            ],
            [
                'tag' => 'Andaman holiday package',
                'link' => ''
            ],
            [
                'tag' => 'Best travel agency for Andaman tours',
                'link' => ''
            ],
            [
                'tag' => 'Travel agency in Andaman',
                'link' => ''
            ],
            [
                'tag' => 'Top Andaman travel agents',
                'link' => ''
            ],
            [
                'tag' => 'Andaman tour operator',
                'link' => ''
            ],
            ['tag' => 'Andaman travel agency tour packages', 'link' => ''],
            ['tag' => 'Andaman travel Agents list', 'link' => ''],
            ['tag' => 'Best travel agency in Andaman', 'link' => ''],
            ['tag' => 'Experience Andaman travel agency', 'link' => ''],
            ['tag' => 'Andaman travel agency contact number', 'link' => ''],
            ['tag' => 'Andaman travel agency price', 'link' => ''],
            ['tag' => 'Andaman travel agency reviews', 'link' => ''],
            ['tag' => 'Andaman travel agency packages', 'link' => ''],
            ['tag' => 'Andaman tour operators in Kolkata', 'link' => ''],
            ['tag' => 'Andaman travel Agents list', 'link' => ''],
            ['tag' => 'Andaman travel agency contact number', 'link' => ''],
            ['tag' => 'Andaman tour operators price', 'link' => ''],
            ['tag' => 'Andaman Tour Operators in Port Blair', 'link' => ''],
            ['tag' => 'Top 10 Andaman Tour Operators', 'link' => ''],
            ['tag' => 'Find Tour Operators in Andaman', 'link' => ''],
            ['tag' => 'Top 10 travel agency in Andaman Nicobar', 'link' => ''],
            ['tag' => 'Travel Agent in Andaman Nicobar', 'link' => ''],
            ['tag' => 'Book Andaman Tour Operators', 'link' => ''],
            ['tag' => 'best tour operator andaman', 'link' => ''],
            ['tag' => 'andaman tour packages', 'link' => ''],
            ['tag' => 'andaman holiday packages', 'link' => ''],
            ['tag' => 'andaman nicobar tour packages', 'link' => ''],
            ['tag' => 'best andaman travel packages', 'link' => ''],
            ['tag' => 'andaman vacation packages', 'link' => ''],
            ['tag' => 'andaman island packages', 'link' => ''],
            ['tag' => 'budget andaman tour package', 'link' => ''],
            ['tag' => 'luxury andaman tour package', 'link' => ''],
            ['tag' => 'all inclusive andaman tour', 'link' => ''],
            ['tag' => 'andaman travel deals', 'link' => ''],
            ['tag' => 'andaman tourism packages', 'link' => ''],
            ['tag' => 'andaman trip package price', 'link' => ''],
            ['tag' => 'andaman itinerary packages', 'link' => ''],
            ['tag' => 'andaman honeymoon and family packages', 'link' => ''],
            ['tag' => 'andaman adventure packages', 'link' => ''],
            ['tag' => 'andaman custom tour packages', 'link' => ''],
            ['tag' => '5 nights andaman package', 'link' => ''],
            ['tag' => '6 nights andaman package', 'link' => ''],
            ['tag' => 'port blair havelock neil package', 'link' => ''],
            ['tag' => 'best andaman tourism deals', 'link' => ''],
            ['tag' => 'Andaman Tour Packages from Delhi', 'link' => ''],
            ['tag' => 'Andaman Tour Package cost', 'link' => ''],
            ['tag' => 'Andaman Tour Packages with flight', 'link' => ''],
            ['tag' => 'Andaman tour package for couple', 'link' => ''],
            ['tag' => 'Andaman Packages with flight price', 'link' => ''],
            ['tag' => 'Andaman Tour Package', 'link' => ''],
            ['tag' => 'Andaman tour packages for family', 'link' => ''],
            ['tag' => 'Andaman tour package from chennai', 'link' => ''],

            ['tag' => 'Andaman Honeymoon Packages from Delhi', 'link' => ''],
            ['tag' => 'Andaman honeymoon package price', 'link' => ''],
            ['tag' => 'Andaman Honeymoon Packages with flight', 'link' => ''],
            ['tag' => 'Andaman honeymoon package for couple', 'link' => ''],
            ['tag' => 'Andaman Nicobar package for couple price', 'link' => ''],
            ['tag' => 'Andaman Honeymoon package for 3 Days', 'link' => ''],
            ['tag' => '6 Nights 7 Days Andaman Honeymoon package', 'link' => ''],
            ['tag' => 'Andaman Honeymoon Package with Scuba diving', 'link' => ''],
            ['tag' => 'andaman honeymoon packages', 'link' => ''],
            ['tag' => 'honeymoon trip to andaman', 'link' => ''],
            ['tag' => 'romantic andaman packages', 'link' => ''],
            ['tag' => 'best honeymoon packages in andaman', 'link' => ''],
            ['tag' => 'andaman couple tour packages', 'link' => ''],
            ['tag' => 'honeymoon in andaman nicobar', 'link' => ''],
            ['tag' => 'luxury honeymoon andaman', 'link' => ''],
            ['tag' => 'affordable andaman honeymoon', 'link' => ''],
            ['tag' => 'andaman beach honeymoon', 'link' => ''],
            ['tag' => '5 nights andaman honeymoon package', 'link' => ''],
            ['tag' => 'private honeymoon package andaman', 'link' => ''],
            ['tag' => 'port blair havelock honeymoon', 'link' => ''],
            ['tag' => 'honeymoon resorts andaman', 'link' => ''],
            ['tag' => 'andaman honeymoon itinerary', 'link' => ''],
            ['tag' => 'honeymoon special andaman trip', 'link' => ''],
            ['tag' => 'newlywed andaman packages', 'link' => ''],
            ['tag' => 'romantic getaway andaman', 'link' => ''],
            ['tag' => 'andaman honeymoon deals', 'link' => ''],
            ['tag' => 'all inclusive honeymoon andaman', 'link' => ''],
            ['tag' => 'customized honeymoon tour andaman', 'link' => ''],

            ['tag' => 'Andaman Nicobar Package for family with flight', 'link' => ''],
            ['tag' => 'Kesari Andaman tour packages for family', 'link' => ''],
            ['tag' => 'Andaman Packages with flight price', 'link' => ''],
            ['tag' => 'Andaman and Nicobar packages including airfare', 'link' => ''],
            ['tag' => 'Make my trip Andaman family Package', 'link' => ''],
            ['tag' => 'Andaman family packages from kolkata', 'link' => ''],
            ['tag' => 'Andaman family Package Price', 'link' => ''],
            ['tag' => 'Andaman and Nicobar package for 4 Person', 'link' => ''],
            ['tag' => 'andaman family packages', 'link' => ''],
            ['tag' => 'family trip to andaman', 'link' => ''],
            ['tag' => 'family holiday packages andaman', 'link' => ''],
            ['tag' => 'best andaman packages for family', 'link' => ''],
            ['tag' => 'andaman kid-friendly packages', 'link' => ''],
            ['tag' => 'safe family tour andaman', 'link' => ''],
            ['tag' => 'affordable family andaman package', 'link' => ''],
            ['tag' => 'andaman group family tour', 'link' => ''],
            ['tag' => 'port blair family trip package', 'link' => ''],
            ['tag' => 'havelock neil family package', 'link' => ''],
            ['tag' => '5 nights family andaman package', 'link' => ''],
            ['tag' => 'andaman holiday for families', 'link' => ''],
            ['tag' => 'customized family packages andaman', 'link' => ''],
            ['tag' => 'andaman sightseeing family tour', 'link' => ''],
            ['tag' => 'budget family andaman trip', 'link' => ''],
            ['tag' => 'premium family package andaman', 'link' => ''],
            ['tag' => 'andaman family itinerary', 'link' => ''],
            ['tag' => 'complete family vacation andaman', 'link' => ''],
            ['tag' => 'andaman nicobar family travel', 'link' => ''],
            ['tag' => 'andaman island family packages', 'link' => ''],
            ['tag' => 'andaman group packages', 'link' => ''],
            ['tag' => 'group trip to andaman', 'link' => ''],
            ['tag' => 'andaman tour packages for groups', 'link' => ''],
            ['tag' => 'corporate group tour andaman', 'link' => ''],
            ['tag' => 'friends group andaman packages', 'link' => ''],
            ['tag' => 'group adventure tour andaman', 'link' => ''],
            ['tag' => 'andaman school group trip', 'link' => ''],
            ['tag' => 'andaman college group packages', 'link' => ''],
            ['tag' => 'large group andaman tour', 'link' => ''],
            ['tag' => 'andaman island group travel', 'link' => ''],
            ['tag' => 'office trip andaman', 'link' => ''],
            ['tag' => 'bachelor trip andaman', 'link' => ''],
            ['tag' => 'budget group tour andaman', 'link' => ''],
            ['tag' => 'premium group package andaman', 'link' => ''],
            ['tag' => 'port blair group trip', 'link' => ''],
            ['tag' => 'havelock group package', 'link' => ''],
            ['tag' => 'customized group tour andaman', 'link' => ''],
            ['tag' => 'andaman nicobar group vacation', 'link' => ''],
            ['tag' => 'best group package andaman', 'link' => ''],
            ['tag' => 'group sightseeing andaman', 'link' => ''],

            ['tag' => 'LTC to Andaman for Central Govt employees', 'link' => ''],
            ['tag' => 'Andaman Itc package for couple', 'link' => ''],
            ['tag' => 'Andaman Itc package price', 'link' => ''],
            ['tag' => 'Andaman Itc package from chennai', 'link' => ''],
            ['tag' => 'Andaman Packages with flight price', 'link' => ''],
            ['tag' => 'IRCTC LTC package For Andaman', 'link' => ''],
            ['tag' => 'Andaman LTC package Balmer Lawrie', 'link' => ''],
            ['tag' => 'andaman ltc packages', 'link' => ''],
            ['tag' => 'ltc approved andaman tour', 'link' => ''],
            ['tag' => 'government ltc andaman packages', 'link' => ''],
            ['tag' => 'andaman ltc tourism', 'link' => ''],
            ['tag' => 'ltc family package andaman', 'link' => ''],
            ['tag' => 'ltc travel to andaman', 'link' => ''],
            ['tag' => 'andaman ltc trip cost', 'link' => ''],
            ['tag' => 'ltc holiday andaman', 'link' => ''],
            ['tag' => 'ltc leave travel andaman', 'link' => ''],
            ['tag' => 'ltc flight package andaman', 'link' => ''],
            ['tag' => 'best ltc package andaman', 'link' => ''],
            ['tag' => 'ltc tour andaman nicobar', 'link' => ''],
            ['tag' => 'ltc sightseeing andaman', 'link' => ''],
            ['tag' => 'andaman nicobar ltc trip', 'link' => ''],
            ['tag' => 'port blair ltc package', 'link' => ''],
            ['tag' => 'andaman islands ltc tour', 'link' => ''],
            ['tag' => 'ltc special package andaman', 'link' => ''],
            ['tag' => 'ltc return flight andaman', 'link' => ''],
            ['tag' => 'ltc family tour andaman', 'link' => ''],
            ['tag' => 'ltc approved destinations andaman', 'link' => ''],

            ['tag' => 'andaman tour packages from chennai', 'link' => ''],
            ['tag' => 'chennai to andaman trip', 'link' => ''],
            ['tag' => 'chennai to andaman flight package', 'link' => ''],
            ['tag' => 'andaman trip cost from chennai', 'link' => ''],
            ['tag' => 'chennai andaman travel packages', 'link' => ''],
            ['tag' => 'andaman holiday from chennai', 'link' => ''],
            ['tag' => 'andaman tourism from chennai', 'link' => ''],
            ['tag' => 'best andaman package from chennai', 'link' => ''],
            ['tag' => 'budget andaman package chennai', 'link' => ''],
            ['tag' => 'chennai to port blair package', 'link' => ''],
            ['tag' => 'chennai to andaman cruise info', 'link' => ''],
            ['tag' => '5 nights andaman package from chennai', 'link' => ''],
            ['tag' => 'honeymoon package from chennai to andaman', 'link' => ''],
            ['tag' => 'family trip andaman from chennai', 'link' => ''],
            ['tag' => 'group tour andaman from chennai', 'link' => ''],
            ['tag' => 'andaman booking from chennai', 'link' => ''],
            ['tag' => 'andaman trip offers chennai', 'link' => ''],
            ['tag' => 'chennai to havelock packages', 'link' => ''],
            ['tag' => 'chennai to neil island package', 'link' => ''],
            ['tag' => 'chennai departure andaman trips', 'link' => ''],

            ['tag' => 'Andaman Tour Packages from Mumbai with flight price', 'link' => ''],
            ['tag' => 'Andaman tour packages from Mumbai', 'link' => ''],
            ['tag' => 'Mumbai to Andaman tour package with flight', 'link' => ''],
            ['tag' => 'Andaman tour packages from numbai for family', 'link' => ''],
            ['tag' => 'Andaman tour packages from Mumbai Kesari', 'link' => ''],
            ['tag' => 'Andaman tour packages from mumbai price', 'link' => ''],
            ['tag' => 'Andaman Packages with flight price', 'link' => ''],
            ['tag' => 'Andaman tour packages from mumbai by train', 'link' => ''],
            ['tag' => 'andaman tour packages from mumbai', 'link' => ''],
            ['tag' => 'mumbai to andaman trip', 'link' => ''],
            ['tag' => 'andaman vacation from mumbai', 'link' => ''],
            ['tag' => 'mumbai to port blair package', 'link' => ''],
            ['tag' => 'holiday packages to andaman from mumbai', 'link' => ''],
            ['tag' => 'andaman flight package mumbai', 'link' => ''],
            ['tag' => 'best andaman package mumbai', 'link' => ''],
            ['tag' => 'family trip to andaman from mumbai', 'link' => ''],
            ['tag' => 'honeymoon package andaman from mumbai', 'link' => ''],
            ['tag' => 'affordable andaman trip mumbai', 'link' => ''],
            ['tag' => 'group tour andaman from mumbai', 'link' => ''],
            ['tag' => 'mumbai to havelock packages', 'link' => ''],
            ['tag' => 'mumbai to andaman travel deals', 'link' => ''],
            ['tag' => 'andaman holidays from mumbai', 'link' => ''],
            ['tag' => 'mumbai to andaman ferry info', 'link' => ''],
            ['tag' => 'andaman trip cost mumbai', 'link' => ''],
            ['tag' => 'luxury andaman package mumbai', 'link' => ''],
            ['tag' => 'student trip andaman from mumbai', 'link' => ''],
            ['tag' => 'port blair package from mumbai', 'link' => ''],
            ['tag' => 'mumbai departure andaman packages', 'link' => ''],

            ['tag' => 'Bangalore to Andaman packages with flight', 'link' => ''],
            ['tag' => 'Andaman tour packages from bangalore for family', 'link' => ''],
            ['tag' => 'Bangalore to Andaman packages with flight price', 'link' => ''],
            ['tag' => 'Bangalore to Andaman flight Andaman Packages from Bangalore by ship', 'link' => ''],
            ['tag' => 'Bangalore to Andaman Packages with flight price for Family', 'link' => ''],
            ['tag' => 'Andaman tour packages from bangalore price', 'link' => ''],
            ['tag' => 'Bangalore to Andaman packages with flight For couple', 'link' => ''],
            ['tag' => 'andaman tour packages from bangalore', 'link' => ''],
            ['tag' => 'bangalore to andaman trip', 'link' => ''],
            ['tag' => 'andaman trip from bangalore', 'link' => ''],
            ['tag' => 'bangalore andaman flight package', 'link' => ''],
            ['tag' => 'best andaman packages from bangalore', 'link' => ''],
            ['tag' => 'holiday packages andaman from bangalore', 'link' => ''],
            ['tag' => 'andaman tourism packages bangalore', 'link' => ''],
            ['tag' => 'bangalore to port blair package', 'link' => ''],
            ['tag' => 'family andaman trip from bangalore', 'link' => ''],
            ['tag' => 'honeymoon package andaman from bangalore', 'link' => ''],
            ['tag' => 'affordable andaman package bangalore', 'link' => ''],
            ['tag' => 'group travel andaman from bangalore', 'link' => ''],
            ['tag' => 'bangalore to havelock trip', 'link' => ''],
            ['tag' => 'andaman package price from bangalore', 'link' => ''],
            ['tag' => 'bangalore to neil island package', 'link' => ''],
            ['tag' => 'weekend trip to andaman from bangalore', 'link' => ''],
            ['tag' => 'luxury andaman package bangalore', 'link' => ''],
            ['tag' => '5 nights andaman trip bangalore', 'link' => ''],
            ['tag' => 'andaman flights from bangalore', 'link' => ''],
            ['tag' => 'bangalore departure andaman packages', 'link' => ''],

            ['tag' => 'Andaman tour packages from delhi for couple', 'link' => ''],
            ['tag' => 'Andaman packages with flight price from Delhi', 'link' => ''],
            ['tag' => 'Andaman Tour Package 2 night: 3 days', 'link' => ''],
            ['tag' => 'Andaman tour packages from delhi price', 'link' => ''],
            ['tag' => 'Andaman Tour Package by cruise', 'link' => ''],
            ['tag' => 'Andaman tour packages from delhi for family', 'link' => ''],
            ['tag' => 'andaman tour packages from delhi', 'link' => ''],
            ['tag' => 'delhi to andaman trip', 'link' => ''],
            ['tag' => 'andaman holiday from delhi', 'link' => ''],
            ['tag' => 'delhi andaman flight packages', 'link' => ''],
            ['tag' => 'best andaman package from delhi', 'link' => ''],
            ['tag' => 'affordable andaman trip delhi', 'link' => ''],
            ['tag' => 'delhi to port blair package', 'link' => ''],
            ['tag' => 'honeymoon andaman from delhi', 'link' => ''],
            ['tag' => 'family andaman trip delhi', 'link' => ''],
            ['tag' => 'group tour andaman from delhi', 'link' => ''],
            ['tag' => 'delhi to havelock package', 'link' => ''],
            ['tag' => 'andaman package price from delhi', 'link' => ''],
            ['tag' => 'delhi to andaman tourism', 'link' => ''],
            ['tag' => 'travel to andaman from delhi', 'link' => ''],
            ['tag' => '5 nights andaman trip delhi', 'link' => ''],
            ['tag' => 'luxury andaman package delhi', 'link' => ''],
            ['tag' => 'delhi andaman flights', 'link' => ''],
            ['tag' => 'andaman booking from delhi', 'link' => ''],
            ['tag' => 'delhi to neil island package', 'link' => ''],
            ['tag' => 'delhi departure andaman packages', 'link' => ''],
            ['tag' => 'Andaman tour packages from bhubaneswar price', 'link' => ''],
            ['tag' => 'Odisha to Andaman by ship', 'link' => ''],
            ['tag' => 'Best andaman tour packages from bhubaneswar', 'link' => ''],
            ['tag' => 'Odisha to Andaman flight price', 'link' => ''],
            ['tag' => 'How to reach Andaman from Bhubaneswar', 'link' => ''],
            ['tag' => 'Bhubaneswar to Andaman flight', 'link' => ''],
            ['tag' => 'andaman tour packages from bhubaneswar', 'link' => ''],
            ['tag' => 'bhubaneswar to andaman trip', 'link' => ''],
            ['tag' => 'andaman holiday from odisha', 'link' => ''],
            ['tag' => 'odisha to andaman tour package', 'link' => ''],
            ['tag' => 'bhubaneswar andaman flight package', 'link' => ''],
            ['tag' => 'best andaman package from bhubaneswar', 'link' => ''],
            ['tag' => 'affordable andaman trip odisha', 'link' => ''],
            ['tag' => 'family andaman trip from bhubaneswar', 'link' => ''],
            ['tag' => 'honeymoon andaman from bhubaneswar', 'link' => ''],
            ['tag' => 'group tour andaman from bhubaneswar', 'link' => ''],
            ['tag' => 'bhubaneswar to port blair package', 'link' => ''],
            ['tag' => 'odisha to andaman tourism', 'link' => ''],
            ['tag' => '5 nights andaman package odisha', 'link' => ''],
            ['tag' => 'andaman travel from bhubaneswar', 'link' => ''],
            ['tag' => 'luxury andaman package bhubaneswar', 'link' => ''],
            ['tag' => 'havelock package from bhubaneswar', 'link' => ''],
            ['tag' => 'odisha to andaman flight deal', 'link' => ''],
            ['tag' => 'budget andaman tour bhubaneswar', 'link' => ''],
            ['tag' => 'bhubaneswar to neil island package', 'link' => ''],
            ['tag' => 'bhubaneswar departure andaman packages', 'link' => ''],

            ['tag' => 'Andaman tour packages from ahmedabad price', 'link' => ''],
            ['tag' => 'Andaman Packages with flight price from Ahmedabad', 'link' => ''],
            ['tag' => 'Andaman tour packages from ahmedabad for couple', 'link' => ''],
            ['tag' => 'Andaman tour packages from ahmedabad for family', 'link' => ''],
            ['tag' => 'daman Nicobar Tour packages Ahmedabad with flight', 'link' => ''],
            ['tag' => 'Andaman tour packages from ahmedabad by train', 'link' => ''],
            ['tag' => 'Ahmedabad to Andaman Nicobar flight', 'link' => ''],
            ['tag' => 'andaman tour packages from ahmedabad', 'link' => ''],
            ['tag' => 'ahmedabad to andaman trip', 'link' => ''],
            ['tag' => 'gujarat to andaman tour package', 'link' => ''],
            ['tag' => 'andaman holiday from ahmedabad', 'link' => ''],
            ['tag' => 'best andaman package gujarat', 'link' => ''],
            ['tag' => 'ahmedabad andaman flight package', 'link' => ''],
            ['tag' => 'affordable andaman tour ahmedabad', 'link' => ''],
            ['tag' => 'honeymoon andaman from ahmedabad', 'link' => ''],
            ['tag' => 'family trip andaman from ahmedabad', 'link' => ''],
            ['tag' => 'group tour andaman from ahmedabad', 'link' => ''],
            ['tag' => 'ahmedabad to port blair travel', 'link' => ''],
            ['tag' => 'andaman package price from ahmedabad', 'link' => ''],
            ['tag' => 'ahmedabad to havelock package', 'link' => ''],
            ['tag' => 'luxury andaman package gujarat', 'link' => ''],
            ['tag' => '6 nights andaman trip ahmedabad', 'link' => ''],
            ['tag' => 'gujarat to andaman tourism', 'link' => ''],
            ['tag' => 'andaman flights from ahmedabad', 'link' => ''],
            ['tag' => 'ahmedabad to neil island package', 'link' => ''],
            ['tag' => 'budget andaman trip ahmedabad', 'link' => ''],
            ['tag' => 'ahmedabad departure andaman packages', 'link' => ''],

            ['tag' => 'andaman tour packages from hyderabad including flights', 'link' => ''],
            ['tag' => 'andaman tour packages from hyderabad for family', 'link' => ''],
            ['tag' => 'best andaman tour packages from hyderabad', 'link' => ''],
            ['tag' => 'ircte andaman package from hyderabad', 'link' => ''],
            ['tag' => 'andaman tour packages hyderabad to andaman flight', 'link' => ''],
            ['tag' => 'Andaman Tour packages from Hyderabad including flights', 'link' => ''],
            ['tag' => 'Andaman tour packages from hyderabad for couple', 'link' => ''],
            ['tag' => 'Andaman tour packages from hyderabad price', 'link' => ''],
            ['tag' => 'andaman tour packages from hyderabad', 'link' => ''],
            ['tag' => 'andaman holiday from hyderabad', 'link' => ''],
            ['tag' => 'hyderabad andaman flight package', 'link' => ''],
            ['tag' => 'best andaman package hyderabad', 'link' => ''],
            ['tag' => 'budget trip to andaman from hyderabad', 'link' => ''],
            ['tag' => 'honeymoon andaman from hyderabad', 'link' => ''],
            ['tag' => 'family andaman package hyderabad', 'link' => ''],
            ['tag' => 'group tour andaman from hyderabad', 'link' => ''],
            ['tag' => 'hyderabad to port blair trip', 'link' => ''],
            ['tag' => 'andaman tourism hyderabad', 'link' => ''],
            ['tag' => 'hyderabad to havelock package', 'link' => ''],
            ['tag' => 'andaman package price from hyderabad', 'link' => ''],
            ['tag' => 'luxury andaman package hyderabad', 'link' => ''],
            ['tag' => 'hyderabad to neil island tour', 'link' => ''],
            ['tag' => 'affordable andaman trip hyderabad', 'link' => ''],
            ['tag' => '5 nights andaman package hyderabad', 'link' => ''],
            ['tag' => 'travel to andaman from hyderabad', 'link' => ''],
            ['tag' => 'hyderabad andaman booking', 'link' => ''],
            ['tag' => 'hyderabad departure andaman packages', 'link' => ''],

            ['tag' => 'andaman tour packages from bihar', 'link' => ''],
            ['tag' => 'bihar to andaman trip', 'link' => ''],
            ['tag' => 'best andaman package bihar', 'link' => ''],
            ['tag' => 'affordable andaman trip bihar', 'link' => ''],
            ['tag' => 'family trip andaman from bihar', 'link' => ''],
            ['tag' => 'honeymoon package andaman from bihar', 'link' => ''],
            ['tag' => 'group tour andaman from bihar', 'link' => ''],
            ['tag' => 'bihar to andaman tourism', 'link' => ''],
            ['tag' => 'andaman package price bihar', 'link' => ''],
            ['tag' => 'bihar to havelock package', 'link' => ''],
            ['tag' => 'bihar andaman flights', 'link' => ''],
            ['tag' => '6 nights andaman trip bihar', 'link' => ''],
            ['tag' => 'budget trip andaman from bihar', 'link' => ''],
            ['tag' => 'bihar to neil island package', 'link' => ''],
            ['tag' => 'andaman tour deals bihar', 'link' => ''],
            ['tag' => 'bihar to andaman cost', 'link' => ''],
            ['tag' => 'bihar departure andaman packages', 'link' => ''],

            ['tag' => 'andaman tour packages from chhattisgarh', 'link' => ''],
            ['tag' => 'chhattisgarh to andaman trip', 'link' => ''],
            ['tag' => 'raipur to andaman tour package', 'link' => ''],
            ['tag' => 'andaman holiday from chhattisgarh', 'link' => ''],
            ['tag' => 'best andaman package raipur', 'link' => ''],
            ['tag' => 'chhattisgarh andaman flights', 'link' => ''],
            ['tag' => 'affordable andaman package raipur', 'link' => ''],
            ['tag' => 'honeymoon andaman from raipur', 'link' => ''],
            ['tag' => 'family trip andaman chhattisgarh', 'link' => ''],
            ['tag' => 'group tour andaman from raipur', 'link' => ''],
            ['tag' => 'raipur to port blair travel', 'link' => ''],
            ['tag' => 'chhattisgarh to havelock package', 'link' => ''],
            ['tag' => 'budget andaman tour raipur', 'link' => ''],
            ['tag' => 'luxury andaman package raipur', 'link' => ''],
            ['tag' => '5 nights andaman package raipur', 'link' => ''],
            ['tag' => 'andaman tourism chhattisgarh', 'link' => ''],
            ['tag' => 'andaman deals from raipur', 'link' => ''],
            ['tag' => 'raipur to neil island package', 'link' => ''],
            ['tag' => 'chhattisgarh to andaman cost', 'link' => ''],
            ['tag' => 'raipur departure andaman packages', 'link' => ''],

            ['tag' => 'andaman tour packages from chandigarh', 'link' => ''],
            ['tag' => 'chandigarh to andaman trip', 'link' => ''],
            ['tag' => 'andaman holiday from chandigarh', 'link' => ''],
            ['tag' => 'chandigarh andaman flight package', 'link' => ''],
            ['tag' => 'best andaman package chandigarh', 'link' => ''],
            ['tag' => 'budget andaman tour chandigarh', 'link' => ''],
            ['tag' => 'honeymoon package andaman from chandigarh', 'link' => ''],
            ['tag' => 'family trip andaman chandigarh', 'link' => ''],
            ['tag' => 'group tour andaman from chandigarh', 'link' => ''],
            ['tag' => 'chandigarh to port blair package', 'link' => ''],
            ['tag' => 'chandigarh to havelock tour', 'link' => ''],
            ['tag' => 'andaman package price chandigarh', 'link' => ''],
            ['tag' => 'luxury andaman package chandigarh', 'link' => ''],
            ['tag' => 'chandigarh to neil island package', 'link' => ''],
            ['tag' => 'andaman tourism chandigarh', 'link' => ''],
            ['tag' => '5 nights andaman package chandigarh', 'link' => ''],
            ['tag' => 'chandigarh to andaman travel deals', 'link' => ''],
            ['tag' => 'affordable andaman trip chandigarh', 'link' => ''],
            ['tag' => 'andaman booking chandigarh', 'link' => ''],
            ['tag' => 'chandigarh departure andaman packages', 'link' => ''],

            ['tag' => 'andaman tour packages from goa', 'link' => ''],
            ['tag' => 'goa to andaman trip', 'link' => ''],
            ['tag' => 'goa to andaman holiday package', 'link' => ''],
            ['tag' => 'goa to port blair flights', 'link' => ''],
            ['tag' => 'andaman travel packages from goa', 'link' => ''],
            ['tag' => 'affordable andaman trip goa', 'link' => ''],
            ['tag' => 'best andaman holiday goa', 'link' => ''],
            ['tag' => 'honeymoon andaman from goa', 'link' => ''],
            ['tag' => 'family trip andaman from goa', 'link' => ''],
            ['tag' => 'group tour andaman from goa', 'link' => ''],
            ['tag' => 'goa to havelock package', 'link' => ''],
            ['tag' => 'andaman package price goa', 'link' => ''],
            ['tag' => 'goa to neil island package', 'link' => ''],
            ['tag' => 'andaman vacation goa departure', 'link' => ''],
            ['tag' => 'luxury andaman package goa', 'link' => ''],
            ['tag' => 'goa andaman travel deals', 'link' => ''],
            ['tag' => 'goa to andaman itinerary', 'link' => ''],
            ['tag' => 'andaman tour cost from goa', 'link' => ''],
            ['tag' => 'goa to port blair travel', 'link' => ''],
            ['tag' => 'goa departure andaman packages', 'link' => ''],

            ['tag' => 'andaman tour packages from assam', 'link' => ''],
            ['tag' => 'assam to andaman trip', 'link' => ''],
            ['tag' => 'guwahati to andaman package', 'link' => ''],
            ['tag' => 'andaman holiday from assam', 'link' => ''],
            ['tag' => 'best andaman package assam', 'link' => ''],
            ['tag' => 'affordable andaman trip assam', 'link' => ''],
            ['tag' => 'honeymoon andaman from guwahati', 'link' => ''],
            ['tag' => 'family trip andaman assam', 'link' => ''],
            ['tag' => 'group tour andaman from assam', 'link' => ''],
            ['tag' => 'assam to port blair flights', 'link' => ''],
            ['tag' => 'assam to havelock package', 'link' => ''],
            ['tag' => 'andaman package price assam', 'link' => ''],
            ['tag' => 'guwahati to neil island package', 'link' => ''],
            ['tag' => 'luxury andaman package assam', 'link' => ''],
            ['tag' => 'budget andaman package assam', 'link' => ''],
            ['tag' => 'andaman tourism assam', 'link' => ''],
            ['tag' => '5 nights andaman trip assam', 'link' => ''],
            ['tag' => 'assam andaman travel deals', 'link' => ''],
            ['tag' => 'andaman trip cost from assam', 'link' => ''],
            ['tag' => 'assam departure andaman packages', 'link' => ''],

            ['tag' => 'andaman tour packages from kolkata', 'link' => ''],
            ['tag' => 'kolkata to andaman trip', 'link' => ''],
            ['tag' => 'kolkata to andaman tour cost', 'link' => ''],
            ['tag' => 'andaman holiday from kolkata', 'link' => ''],
            ['tag' => 'andaman travel packages kolkata', 'link' => ''],
            ['tag' => 'best andaman package from kolkata', 'link' => ''],
            ['tag' => 'affordable andaman trip kolkata', 'link' => ''],
            ['tag' => 'family trip andaman kolkata', 'link' => ''],
            ['tag' => 'honeymoon andaman from kolkata', 'link' => ''],
            ['tag' => 'group tour andaman from kolkata', 'link' => ''],
            ['tag' => 'kolkata to port blair flights', 'link' => ''],
            ['tag' => 'kolkata to havelock package', 'link' => ''],
            ['tag' => 'kolkata to neil island package', 'link' => ''],
            ['tag' => 'andaman tour price kolkata', 'link' => ''],
            ['tag' => '6 nights andaman package kolkata', 'link' => ''],
            ['tag' => 'andaman tourism kolkata', 'link' => ''],
            ['tag' => 'kolkata to andaman travel deals', 'link' => ''],
            ['tag' => 'budget andaman package kolkata', 'link' => ''],
            ['tag' => 'luxury andaman package kolkata', 'link' => ''],
            ['tag' => 'kolkata departure andaman packages', 'link' => '']
        ];
        foreach ($tags as $tag) {
            Tags::updateOrCreate([
                'tag' => $tag['tag'],
                'link' => ''
            ]);
        }
    }
}
